name: 'Push - Raspberry Pi ARMv8 Scarthgap'

on:
  push:
    paths:
      - '**'
      - '.github/**'
      - '.github/configs/**'

jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/shared-vols.yaml
      name: raspberrypi-armv8-scarthgap
    secrets: inherit
