name: PUSH master
on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/raspberrypi-armv8-scarthgap.yaml

  colibri:
    uses: ./.github/workflows/colibri.yaml
