name: 'Push - Raspberry Pi ARMv8 Scarthgap'

on:
  workflow_call:


jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas.yml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yml:.github/configs/shared-vols.yml
      name: raspberrypi-armv8-scarthgap
    secrets: inherit
