# This is a basic workflow to help you get started with Actions

name: TAG

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: print
        run: |
          echo  tag: ${{ github.ref }}
          echo  tag - ${{ steps.tag.outputs.tag_name }}
